#!/usr/bin/env node
// scripts/generate-index.mjs — builds KnowledgeBase/BoardGames/INDEX.okf.md,
// the machine twin of index.html (OKF 0.2 §2). Zero dependencies.
//
//   node scripts/generate-index.mjs          # regenerate INDEX.okf.md
//   node scripts/generate-index.mjs --check  # exit 1 if the file on disk is stale
//
// Deterministic: derived only from frontmatter of games/**/*.okf.md, games
// and mechanics sorted. Regenerated at the end of every scout run and by the
// librarian; freshness is enforced by scripts/validate-okf.mjs.

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { logScan } from './telemetry-log.mjs'

const ROOT = 'KnowledgeBase/BoardGames'
const INDEX_FILE = path.join(ROOT, 'INDEX.okf.md')

const frontmatter = text => text.match(/^---\r?\n([\s\S]*?)\r?\n---/)?.[1] ?? ''
const field = (head, name) =>
  head.match(new RegExp(`^${name}:\\s*(.*)$`, 'm'))?.[1]?.trim().replace(/^["']|["']$/g, '')
const gameField = (head, name) =>
  head.match(new RegExp(`^\\s+${name}:\\s*(.*)$`, 'm'))?.[1]?.trim().replace(/^["']|["']$/g, '')
const list = (head, name) => {
  const inline = head.match(new RegExp(`^${name}:\\s*\\[(.*)\\]`, 'm'))
  if (inline) return inline[1].split(',').map(s => s.trim().replace(/^["']|["']$/g, '')).filter(Boolean)
  const block = head.match(new RegExp(`^${name}:\\s*\\r?\\n((?:\\s+-\\s+.*\\r?\\n?)+)`, 'm'))
  if (block) return [...block[1].matchAll(/-\s+"?([^"\r\n]+)"?/g)].map(m => m[1].trim())
  return []
}

function* okfFiles(dir) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
    const p = path.join(dir, entry.name)
    if (entry.isDirectory()) yield* okfFiles(p)
    else if (entry.name.endsWith('.okf.md')) yield p
  }
}

export function buildIndex(root = ROOT) {
  const gamesDir = path.join(root, 'games')
  const slugs = fs.existsSync(gamesDir)
    ? fs.readdirSync(gamesDir, { withFileTypes: true }).filter(e => e.isDirectory()).map(e => e.name).sort()
    : []

  const rows = []
  const byMechanic = new Map()

  for (const slug of slugs) {
    const dir = path.join(gamesDir, slug)
    const docs = [...okfFiles(dir)]
    const statuses = new Map()
    let title = slug, year = '', weight = '', mechanics = [], visualRefs = 0
    const labelOrder = []

    for (const file of docs) {
      const head = frontmatter(fs.readFileSync(file, 'utf-8'))
      const status = field(head, 'status') ?? 'unknown'
      statuses.set(status, (statuses.get(status) ?? 0) + 1)
      if (path.basename(file) === 'index.okf.md') {
        title = gameField(head, 'title') || slug
        year = gameField(head, 'year') ?? ''
        weight = gameField(head, 'weight') ?? ''
        mechanics = list(head, 'mechanics')
      }
      if (path.basename(file) === 'packet.okf.md' && path.basename(path.dirname(file)) === 'visuals') {
        visualRefs = [...head.matchAll(/^\s+- id:\s*"?vis-\d{3}"?/gm)].length
      }
      for (const l of list(head, 'better_if_labels')) {
        if (!labelOrder.includes(l)) labelOrder.push(l)
      }
    }

    for (const m of mechanics) {
      if (!byMechanic.has(m)) byMechanic.set(m, [])
      byMechanic.get(m).push(slug)
    }

    const status = statuses.size === 1 && statuses.has('verified')
      ? 'verified'
      : [...statuses.entries()].sort((a, b) => a[0].localeCompare(b[0])).map(([s, n]) => `${s}:${n}`).join(' ')

    const visuals = visualRefs
      ? `[packet](games/${slug}/visuals/packet.okf.md) · [sheet](games/${slug}/visuals/contact-sheet.webp)`
      : ''
    rows.push(`| ${slug} | ${title} | ${year || '?'} | ${weight || '?'} | ${mechanics.join(', ')} | ${labelOrder.slice(0, 5).join(', ')} | ${visualRefs} | ${visuals} | ${status} | ${docs.length} |`)
  }

  const mechanicRows = [...byMechanic.entries()]
    .sort((a, b) => a[0].localeCompare(b[0]))
    .map(([m, games]) => `| ${m} | ${games.join(', ')} |`)

  return `<!-- GENERATED by scripts/generate-index.mjs — do not edit by hand.
     Regenerate: node scripts/generate-index.mjs
     Freshness is enforced by scripts/validate-okf.mjs. -->

# Corpus index — SomberSoft Board Game Knowledge Base

Machine twin of \`index.html\`. One row per game; status aggregates every
doc in the game dir (\`verified\` means all docs verified). Weight is the
BGG complexity weight from the game's discovery source.

## Games

| slug | title | year | weight | mechanics | top better-if labels | visual refs | visual packet | status | docs |
|---|---|---|---|---|---|---|---|---|---|
${rows.join('\n')}

## Mechanics → games

| mechanic | games |
|---|---|
${mechanicRows.join('\n')}
`
}

// fileURLToPath, not URL.pathname: the pathname form ('/C:/...') never
// equals path.resolve ('C:\...') on Windows, silently skipping main.
const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)
if (isMain) {
  const expected = buildIndex()
  if (process.argv.includes('--check')) {
    const actual = fs.existsSync(INDEX_FILE) ? fs.readFileSync(INDEX_FILE, 'utf-8') : null
    if (actual !== expected) {
      console.error(`generate-index: ${INDEX_FILE} is stale — run: node scripts/generate-index.mjs`)
      process.exit(1)
    }
    console.log(`generate-index: ${INDEX_FILE} is fresh`)
  }
  else {
    fs.writeFileSync(INDEX_FILE, expected)
    console.log(`generate-index: wrote ${INDEX_FILE}`)
    const games = expected.match(/^\| [^|]+ \|/gm)?.length ?? 0
    logScan({
      pass: 'generate-index',
      scope: 'games/**/*.okf.md frontmatter',
      scanned: `${games} table rows`,
      findings: 0,
      complete: true,
      note: `wrote ${INDEX_FILE.replaceAll('\\', '/')}`,
    })
  }
}
